package com.vibeos.app.ui

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.*
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.vibeos.app.model.Catalog
import com.vibeos.app.model.ThemePack
import com.vibeos.app.services.AppServices
import com.vibeos.app.services.ThemeGenerationService
import kotlinx.coroutines.delay

@Composable
fun CreateScreen(onPremium: () -> Unit) {
    var prompt by remember { mutableStateOf("Rainy Tokyo, dark glass, neon") }
    var selectedPhoto by remember { mutableStateOf<String?>(null) }
    var generating by remember { mutableStateOf(false) }
    var generated by remember { mutableStateOf<ThemePack?>(null) }

    val photoPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        selectedPhoto = uri?.toString()
        if (uri != null) {
            AppServices.analytics.log("ai_source_selected", mapOf("source" to "photo"))
        }
    }

    LaunchedEffect(generating) {
        if (generating) {
            delay(850)
            generated = ThemeGenerationService.generate(
                if (selectedPhoto != null) prompt + " photo" else prompt
            )
            generating = false
            AppServices.analytics.log("ai_theme_generate_complete")
        }
    }

    LazyColumn(
        Modifier.fillMaxSize(),
        contentPadding = PaddingValues(18.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        item { SectionHeader("AI Theme Studio", "Turn a photo or an idea into a complete setup.") }

        item {
            GlassCard(Modifier.fillMaxWidth()) {
                val result = generated
                if (result == null) {
                    Box(
                        Modifier.fillMaxWidth().height(220.dp).clip(RoundedCornerShape(22.dp))
                            .background(Brush.linearGradient(listOf(Color(0xFF181B28), Color(0xFF5326A0), Color(0xFF172C55)))),
                        contentAlignment = Alignment.Center
                    ) {
                        Text(if (selectedPhoto == null) "＋" else "✓", color = Color.White, fontSize = 62.sp, fontWeight = FontWeight.ExtraLight)
                    }
                } else {
                    ThemePhonePreview(result, Modifier.fillMaxWidth().height(300.dp))
                }
                Spacer(Modifier.height(14.dp))
                Text(
                    if (result == null) "Create a theme from any photo" else "Your theme is ready",
                    color = Color.White,
                    fontWeight = FontWeight.Black,
                    fontSize = 18.sp
                )
                Text(
                    if (selectedPhoto == null) "Photo → palette → wallpaper → icons → widgets" else "Photo selected. Add a vibe description below.",
                    color = VibeColors.Muted,
                    fontSize = 12.sp
                )
            }
        }

        item {
            VibeSecondaryButton(
                if (selectedPhoto == null) "Choose a Photo" else "Change Photo",
                Modifier.fillMaxWidth()
            ) { photoPicker.launch("image/*") }
        }

        item {
            Text("Describe your dream theme", color = Color.White, fontWeight = FontWeight.Bold)
            Spacer(Modifier.height(8.dp))
            BasicTextField(
                value = prompt,
                onValueChange = { prompt = it.take(180) },
                textStyle = TextStyle(color = Color.White, fontSize = 14.sp),
                modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(18.dp))
                    .background(Color.White.copy(.06f))
                    .border(1.dp, Color.White.copy(.10f), RoundedCornerShape(18.dp))
                    .padding(16.dp)
            )
        }

        item {
            Row(
                Modifier.horizontalScroll(rememberScrollState()),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                listOf("Glass", "Minimal", "Anime", "Nature", "Cute", "Cyber", "Luxury").forEach { tag ->
                    VibePill(tag) {
                        prompt = (prompt + ", " + tag.lowercase()).take(180)
                    }
                }
            }
        }

        item {
            VibeButton(
                when {
                    generating -> "Creating…"
                    generated != null -> "Apply Generated Theme"
                    else -> "Generate My Theme"
                },
                Modifier.fillMaxWidth(),
                enabled = !generating
            ) {
                if (generated != null) {
                    onPremium()
                } else {
                    generating = true
                    AppServices.analytics.log(
                        "ai_theme_generate_start",
                        mapOf("source" to if (selectedPhoto == null) "text" else "photo")
                    )
                }
            }
        }
    }
}

@Composable
fun MyScreen(onPremium: () -> Unit, onNotifications: () -> Unit) {
    LazyColumn(
        Modifier.fillMaxSize(),
        contentPadding = PaddingValues(18.dp),
        verticalArrangement = Arrangement.spacedBy(15.dp)
    ) {
        item { SectionHeader("My Screen", "Your themes, streak and personalization.") }

        item {
            GlassCard(Modifier.fillMaxWidth()) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text("🔥", fontSize = 34.sp)
                    Spacer(Modifier.width(12.dp))
                    Column(Modifier.weight(1f)) {
                        Text("3 day vibe streak", color = Color.White, fontSize = 18.sp, fontWeight = FontWeight.Black)
                        Text("Come back tomorrow for a fresh Daily Drop.", color = VibeColors.Muted, fontSize = 12.sp)
                    }
                    Text("+25", color = VibeColors.Gold, fontWeight = FontWeight.Black)
                }
            }
        }

        item {
            Text("My Themes", color = Color.White, fontSize = 18.sp, fontWeight = FontWeight.Black)
            Spacer(Modifier.height(10.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                Catalog.themes.take(2).forEach { theme ->
                    MiniThemeCard(theme, Modifier.weight(1f))
                }
            }
        }

        item { VibeButton("♛  Upgrade to Premium", Modifier.fillMaxWidth(), onClick = onPremium) }

        item {
            VibeSecondaryButton("Enable Daily Drop Notifications", Modifier.fillMaxWidth()) {
                onNotifications()
                AppServices.analytics.log("notification_permission_prompt")
            }
        }

        item {
            VibeSecondaryButton("Restore Purchases", Modifier.fillMaxWidth()) {
                AppServices.purchases.restore { restored ->
                    AppServices.analytics.log("restore_purchase_result", mapOf("restored" to restored.toString()))
                }
            }
        }
    }
}

@Composable
private fun MiniThemeCard(theme: ThemePack, modifier: Modifier) {
    Column(modifier) {
        Box(
            Modifier.fillMaxWidth().height(160.dp).clip(RoundedCornerShape(22.dp))
                .background(Brush.linearGradient(listOf(vibeColor(theme.accentA), vibeColor(theme.accentB), Color.Black)))
        ) {
            Text("9:41", color = Color.White, fontSize = 28.sp, modifier = Modifier.align(Alignment.Center))
        }
        Spacer(Modifier.height(7.dp))
        Text(theme.name, color = Color.White, fontWeight = FontWeight.Bold, fontSize = 13.sp)
    }
}
